import type { AircraftSpec } from "../Types";

export const FLEET: AircraftSpec[] = [
  {
    id: "dhc6_twin_otter",
    name: "Bush Twin Otter",
    class: "turboprop_twin",
    description: "Twin turboprop STOL workhorse for mountain and airport ops",
    massKg: 4500,
    wingAreaM2: 39.0,
    aspectRatio: 8.7,
    maxThrustN: 7800,
    stallSpeedMs: 24,
    maxSpeedMs: 123,
    cruiseSpeedMs: 88,
    stallAoADeg: 16,
    flapLiftFactor: 1.55,
    flapDragFactor: 1.85,
    gearDragFactor: 1.65,
    fuelCapacityKg: 1080,
    fuelBurnKgS: 0.16,
    visualScale: 1.05,
    unlocked: true,
    cockpitModelUrl: null,
    cockpitModelScale: 1,
    exteriorModelUrl: "/models/aircraft/dhc6_twin_otter.glb",
    exteriorModelScale: 1,
    physics: {
      wingSpanM: 19.81,
      macM: 2.3,
      inertia: {
        Ixx: 15200,
        Iyy: 19200,
        Izz: 27800,
        Ixz: 0,
      },
      propulsion: {
        maxThrustN: 7800,
        densityExponent: 0.88,
        staticThrustFactor: 1.55,
      },
      gear: {
        muRoll: 0.035,
        muBrake: 0.52,
        cdGear: 0.03,
        cgHeightM: 1.4,
      },
      flaps: {
        dCl: 0.62,
        dCd: 0.14,
        dCm: -0.08,
      },
      aero: {
        Cl0: 0.38,
        ClAlpha: 5.25,
        ClQ: 4.35,
        ClDe: 0.38,
        Cd0: 0.032,
        inducedDragK: 0.048,
        CyBeta: -0.45,
        CyDr: 0.18,
        ClBeta: -0.12,
        ClP: -0.52,
        ClR: 0.12,
        ClDa: 0.22,
        ClDr: 0.03,
        Cm0: 0.03,
        CmAlpha: -0.84,
        CmQ: -13.5,
        CmDe: -1.18,
        CnBeta: 0.11,
        CnP: -0.03,
        CnR: -0.17,
        CnDa: -0.025,
        CnDr: -0.1,
        alphaStallRad: 16 * Math.PI / 180,
        oswaldE: 0.8,
      },
    },
  },
  {
    id: "cirrus_sr22",
    name: "SkyTrainer SR",
    class: "sep",
    description: "Single-engine prop — forgiving trainer for Free Flight",
    massKg: 1400,
    wingAreaM2: 13.5,
    aspectRatio: 10.3,
    maxThrustN: 4200,
    stallSpeedMs: 31,
    maxSpeedMs: 95,
    cruiseSpeedMs: 72,
    stallAoADeg: 15,
    flapLiftFactor: 1.35,
    flapDragFactor: 1.55,
    gearDragFactor: 1.25,
    fuelCapacityKg: 140,
    fuelBurnKgS: 0.012,
    visualScale: 1,
    unlocked: true,
    // Cockpit GLBs not in repo yet — leave null to avoid 404 + empty windshield
    cockpitModelUrl: null,
    cockpitModelScale: 1,
    exteriorModelUrl: "/models/aircraft/cirrus_sr22.glb",
    exteriorModelScale: 1,
  },
  {
    id: "baron_b58",
    name: "TwinStar B",
    class: "tep",
    description: "Twin-engine prop — higher cruise and climb",
    massKg: 2400,
    wingAreaM2: 17.5,
    aspectRatio: 7.2,
    maxThrustN: 7800,
    stallSpeedMs: 36,
    maxSpeedMs: 120,
    cruiseSpeedMs: 95,
    stallAoADeg: 14,
    flapLiftFactor: 1.3,
    flapDragFactor: 1.5,
    gearDragFactor: 1.3,
    fuelCapacityKg: 280,
    fuelBurnKgS: 0.028,
    visualScale: 1.15,
    unlocked: true,
    cockpitModelUrl: null,
    cockpitModelScale: 1,
  },
  {
    id: "citation_cj",
    name: "Horizon CJ",
    class: "business_jet",
    description: "Light business jet — fast cruise, higher stall",
    massKg: 5600,
    wingAreaM2: 22,
    aspectRatio: 8.8,
    maxThrustN: 22000,
    stallSpeedMs: 48,
    maxSpeedMs: 220,
    cruiseSpeedMs: 180,
    stallAoADeg: 13,
    flapLiftFactor: 1.4,
    flapDragFactor: 1.7,
    gearDragFactor: 1.4,
    fuelCapacityKg: 1200,
    fuelBurnKgS: 0.085,
    visualScale: 1.35,
    unlocked: true,
    cockpitModelUrl: null,
    cockpitModelScale: 1,
    exteriorModelUrl: "/models/aircraft/citation_cj.glb",
    exteriorModelScale: 1,
  },
];

export function getAircraftSpec(id: string): AircraftSpec {
  return FLEET.find((a) => a.id === id) ?? FLEET[0];
}
