import type { AircraftSpec } from "../Types";

export const FLEET: AircraftSpec[] = [
  {
    id: "cirrus_sr22",
    name: "SkyTrainer SR",
    class: "sep",
    description: "Single-engine prop — forgiving trainer for Free Flight",
    massKg: 1400,
    wingAreaM2: 13.5,
    aspectRatio: 10.3,
    maxThrustN: 4200,
    stallSpeedMs: 31,
    maxSpeedMs: 95,
    cruiseSpeedMs: 72,
    stallAoADeg: 15,
    flapLiftFactor: 1.35,
    flapDragFactor: 1.55,
    gearDragFactor: 1.25,
    fuelCapacityKg: 140,
    fuelBurnKgS: 0.012,
    visualScale: 1,
    unlocked: true,
    // Cockpit GLBs not in repo yet — leave null to avoid 404 + empty windshield
    cockpitModelUrl: null,
    cockpitModelScale: 1,
    exteriorModelUrl: "/models/aircraft/cirrus_sr22.glb",
    exteriorModelScale: 1,
  },
  {
    id: "baron_b58",
    name: "TwinStar B",
    class: "tep",
    description: "Twin-engine prop — higher cruise and climb",
    massKg: 2400,
    wingAreaM2: 17.5,
    aspectRatio: 7.2,
    maxThrustN: 7800,
    stallSpeedMs: 36,
    maxSpeedMs: 120,
    cruiseSpeedMs: 95,
    stallAoADeg: 14,
    flapLiftFactor: 1.3,
    flapDragFactor: 1.5,
    gearDragFactor: 1.3,
    fuelCapacityKg: 280,
    fuelBurnKgS: 0.028,
    visualScale: 1.15,
    unlocked: true,
    cockpitModelUrl: null,
    cockpitModelScale: 1,
  },
  {
    id: "citation_cj",
    name: "Horizon CJ",
    class: "business_jet",
    description: "Light business jet — fast cruise, higher stall",
    massKg: 5600,
    wingAreaM2: 22,
    aspectRatio: 8.8,
    maxThrustN: 22000,
    stallSpeedMs: 48,
    maxSpeedMs: 220,
    cruiseSpeedMs: 180,
    stallAoADeg: 13,
    flapLiftFactor: 1.4,
    flapDragFactor: 1.7,
    gearDragFactor: 1.4,
    fuelCapacityKg: 1200,
    fuelBurnKgS: 0.085,
    visualScale: 1.35,
    unlocked: true,
    cockpitModelUrl: null,
    cockpitModelScale: 1,
    exteriorModelUrl: "/models/aircraft/citation_cj.glb",
    exteriorModelScale: 1,
  },
];

export function getAircraftSpec(id: string): AircraftSpec {
  return FLEET.find((a) => a.id === id) ?? FLEET[0];
}
