import type { DryEarthFeature } from "./types";

/**
 * Curated ocean + land features for progressive Dry Earth labels.
 * Coordinates approximate feature centroids / iconic points.
 */
export const DRY_EARTH_FEATURES: DryEarthFeature[] = [
  // ── Ocean trenches ──
  {
    id: "mariana",
    name: "Mariana Trench",
    kind: "trench",
    lat: 11.35,
    lng: 142.2,
    elevM: -10994,
    minZoom: 2,
    revealBelowM: -2000,
  },
  {
    id: "puerto-rico",
    name: "Puerto Rico Trench",
    kind: "trench",
    lat: 19.7,
    lng: -66.5,
    elevM: -8400,
    minZoom: 2,
    revealBelowM: -1500,
  },
  {
    id: "java",
    name: "Java Trench",
    kind: "trench",
    lat: -10.5,
    lng: 110.0,
    elevM: -7200,
    minZoom: 2,
    revealBelowM: -1500,
  },
  {
    id: "tonga",
    name: "Tonga Trench",
    kind: "trench",
    lat: -22.5,
    lng: -174.0,
    elevM: -10800,
    minZoom: 2,
    revealBelowM: -2000,
  },
  {
    id: "peru-chile",
    name: "Peru–Chile Trench",
    kind: "trench",
    lat: -23.0,
    lng: -71.5,
    elevM: -8065,
    minZoom: 2,
    revealBelowM: -1500,
  },
  {
    id: "japan",
    name: "Japan Trench",
    kind: "trench",
    lat: 38.5,
    lng: 144.0,
    elevM: -8000,
    minZoom: 3,
    revealBelowM: -1500,
  },
  // ── Ridges / rises ──
  {
    id: "mar",
    name: "Mid-Atlantic Ridge",
    kind: "ridge",
    lat: 0.0,
    lng: -30.0,
    elevM: -2500,
    minZoom: 1,
    revealBelowM: -500,
  },
  {
    id: "epr",
    name: "East Pacific Rise",
    kind: "rise",
    lat: -10.0,
    lng: -110.0,
    elevM: -2500,
    minZoom: 2,
    revealBelowM: -500,
  },
  {
    id: "cir",
    name: "Central Indian Ridge",
    kind: "ridge",
    lat: -20.0,
    lng: 68.0,
    elevM: -2800,
    minZoom: 3,
    revealBelowM: -800,
  },
  // ── Shelf / slope / basins ──
  {
    id: "shelf-na",
    name: "N. Atlantic Shelf",
    kind: "shelf",
    lat: 40.0,
    lng: -70.0,
    elevM: -80,
    minZoom: 3,
    revealBelowM: 50,
  },
  {
    id: "slope-na",
    name: "Continental Slope",
    kind: "shelf",
    lat: 38.5,
    lng: -72.5,
    elevM: -1500,
    minZoom: 4,
    revealBelowM: -200,
  },
  {
    id: "pacific-basin",
    name: "Pacific Basin",
    kind: "basin",
    lat: 0.0,
    lng: -160.0,
    elevM: -4500,
    minZoom: 1,
    revealBelowM: -2000,
  },
  {
    id: "atlantic-basin",
    name: "Atlantic Basin",
    kind: "basin",
    lat: 20.0,
    lng: -40.0,
    elevM: -4000,
    minZoom: 2,
    revealBelowM: -1500,
  },
  {
    id: "loihi",
    name: "Lōʻihi Seamount",
    kind: "seamount",
    lat: 18.92,
    lng: -155.27,
    elevM: -975,
    minZoom: 4,
    revealBelowM: 0,
  },
  // ── Land peaks / ranges ──
  {
    id: "everest",
    name: "Mount Everest",
    kind: "peak",
    lat: 27.9881,
    lng: 86.925,
    elevM: 8849,
    minZoom: 2,
    revealAboveM: -500,
  },
  {
    id: "k2",
    name: "K2",
    kind: "peak",
    lat: 35.8825,
    lng: 76.5133,
    elevM: 8611,
    minZoom: 3,
    revealAboveM: -500,
  },
  {
    id: "himalayas",
    name: "Himalayas",
    kind: "range",
    lat: 28.5,
    lng: 84.0,
    elevM: 6000,
    minZoom: 1,
  },
  {
    id: "andes",
    name: "Andes",
    kind: "range",
    lat: -20.0,
    lng: -67.0,
    elevM: 5000,
    minZoom: 1,
  },
  {
    id: "rockies",
    name: "Rocky Mountains",
    kind: "range",
    lat: 45.0,
    lng: -113.0,
    elevM: 3500,
    minZoom: 2,
  },
  {
    id: "alps",
    name: "Alps",
    kind: "range",
    lat: 46.5,
    lng: 10.0,
    elevM: 3500,
    minZoom: 3,
  },
  {
    id: "sahara",
    name: "Sahara",
    kind: "desert",
    lat: 23.0,
    lng: 10.0,
    elevM: 400,
    minZoom: 1,
  },
  {
    id: "gobi",
    name: "Gobi Desert",
    kind: "desert",
    lat: 42.5,
    lng: 105.0,
    elevM: 1000,
    minZoom: 2,
  },
  {
    id: "amazon",
    name: "Amazon Basin",
    kind: "basin",
    lat: -3.0,
    lng: -60.0,
    elevM: 100,
    minZoom: 2,
  },
  {
    id: "rift",
    name: "Great Rift Valley",
    kind: "valley",
    lat: 0.5,
    lng: 36.0,
    elevM: 800,
    minZoom: 2,
  },
  {
    id: "nile",
    name: "Nile",
    kind: "river",
    lat: 15.0,
    lng: 32.5,
    elevM: 200,
    minZoom: 3,
  },
  {
    id: "amazon-river",
    name: "Amazon River",
    kind: "river",
    lat: -2.0,
    lng: -55.0,
    elevM: 50,
    minZoom: 3,
  },
  {
    id: "caspian",
    name: "Caspian Sea",
    kind: "lake",
    lat: 42.0,
    lng: 50.0,
    elevM: -28,
    minZoom: 2,
  },
  {
    id: "baikal",
    name: "Lake Baikal",
    kind: "lake",
    lat: 53.5,
    lng: 108.0,
    elevM: 455,
    minZoom: 3,
  },
];
